#!/usr/bin/env ruby
require 'find'
require 'fileutils'

build = ARGV.any? {|a| a =~ /-b/}
refresh = ARGV.any? {|a| a =~ /-r/}
tests = ARGV.any? {|a| a =~ /-t/}
gui = ARGV.any? {|a| a =~ /-g/}
logscript = ARGV.any? {|a| a =~ /-s/}
interactive = ARGV.any? {|a| a =~ /-i/}
database = ARGV.any? {|a| a =~ /-d/ }

classpath = "build/logzilla.jar"
Find.find("lib") do |p|
  if p =~ /.jar$/
    classpath += ":#{p}"
  end
end

system("echo classpath = #{classpath}")

if build
  system("ant jar") or fail
end

if refresh
  system("cp -rv src/clojure/* build/classes/") 
  system("rm -v build/logzilla.jar")
  system("ant just-jar") or fail
end

script = false
  
if tests 
  script = '''
(load \"tparser\")
(tparser/run-tests)
(load \"tlas\")
(tlas/run-tests)
'''
elsif gui
  script = """
(use 'app.controller)
(run-main)
"""
elsif logscript
  script = """
(load-file \\\"#{ARGV.last}\\\")
"""
elsif database
  script = """
(use 'database)
"""
end

system("echo \"classpath =#{classpath}\"")

if script
  system("echo \"#{script}\"")
  system("echo \"#{script}\" | java -cp #{classpath} clojure.main -")
elsif interactive
  system("java -cp #{classpath} clojure.main")
end

